# Generated by Django 2.1.2 on 2018-11-08 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(default=uuid.UUID('28f1b606-0ce6-4007-b332-c022793740f6'), max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('do_by', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
